apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2q7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2q7o
    app.kubernetes.io/part-of: tkrw-pr712-0075-0047-app
  name: devfile-sample-2q7o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2q7o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2q7o
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-2q7o@sha256:b298b045eafe113da8662908270cb8e2a60dc6cb456606d9ad1817211afb4ad6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
